name: Publish iOS

defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11
          cache: 'gradle'
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.0'
      - name: Cache Konan
        id: cache-konan
        uses: actions/cache@v3
        with:
          path: ~/.konan/
          key: konan
      - uses: burrunan/gradle-cache-action@v1
        name: Build XCFramework
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_11 }}
        with:
          job-id: publish-ci
          concurrent: true
          arguments: :assembleAuthlibReleaseXCFramework
      - name: Make release
        run: |
          set -x
          assets=()
          for asset in ${{ github.workspace }}/build/XCFrameworks/release/*.zip; do
            assets+=("-a" "$asset")
          done
          hub release create "${assets[@]}" -m "${{ github.ref }}" "${{ github.ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}