name: Publish iOS

defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11
          cache: 'gradle'
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.0'
      - name: Build XCFramework
        run: JAVA_HOME=$JAVA_HOME_11 ./gradlew :assembleXCFramework --no-daemon
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/XCframeworks/release/authlib.xcframework