name: Publish common release Artifact to GitHub packages and make GitHub release

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

env:
  ORG_GRADLE_PROJECT_HEDVIG_GITHUB_PACKAGES_USER: ${{ secrets.HEDVIG_GITHUB_PACKAGES_USER }}
  ORG_GRADLE_PROJECT_HEDVIG_GITHUB_PACKAGES_TOKEN: ${{ secrets.HEDVIG_GITHUB_PACKAGES_TOKEN }}

jobs:
  publish:
    name: Release build and publish
    runs-on: macos-12
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: 'zulu'
          java-version: 14

      - name: Build
        id: gradle
        uses: gradle/gradle-build-action@v2.3.3

      - name: Publish to GitHub packages
        run: ./gradlew publishAllPublicationsToMavenRepository

      - name: Create release
        uses: softprops/action-gh-release@v1
