name: Publish common release Artifact to GitHub packages and make GitHub release

on:
  push:
    tags:
      - '**'

permissions:
  contents: write
  packages: write

env:
  ORG_GRADLE_PROJECT_HEDVIG_GITHUB_PACKAGES_USER: ${{ secrets.HEDVIG_GITHUB_PACKAGES_USER }}
  ORG_GRADLE_PROJECT_HEDVIG_GITHUB_PACKAGES_TOKEN: ${{ secrets.HEDVIG_GITHUB_PACKAGES_TOKEN }}

jobs:
  publish:
    name: Release build and publish
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 20

      - name: Build
        id: gradle
        uses: gradle/gradle-build-action@v2.12.0

      - name: Publish to GitHub packages
        run: ./gradlew publishAllPublicationsToMavenRepository

      - name: Create release
        uses: softprops/action-gh-release@v1
